---
title: "Assignment2"
subtitle: "STAE04/DABN19: Data Visualization"
author: "Roshan Talimi"
date: "`r Sys.Date()`"
papersize: a4
geometry: margin=4cm
colorlinks: true
output:
  pdf_document:
    number_sections: true
---

```{r include = FALSE}
#https://raw.githubusercontent.com/stat-lu/dataviz/main/template.Rmd"
```

```{r setup, include = FALSE}
# Setup options for R Markdown
knitr::opts_chunk$set(
  echo       = FALSE,    # Do not print code
  warning    = FALSE,    # Suppress warnings
  message    = FALSE,    # Suppress messages
  fig.align  = "center", # Center figures
  fig.width  = 2.7,      # Good standard figure width for single-panel figures
  fig.height = 2.4       # Good standard figure height for single-panel figures
)

library(tidyverse)

# Set a theme for ggplot2
theme_set(theme_light(base_size = 15))

# Set options
options(
  digits = 3, # limit the number of significant digits
  width  = 63 # limit the width of code output
)
```

```{r}
abalone_raw <- read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data", col_names = FALSE)
```


Task 1

* Where and when was this data collected
* How many observations and variables are there
* What are the variables? Describe each in terms of its units of measurement and it’s data type (continuous, integer, or categorical/nominal).


```{r echo=TRUE}

```



Task 2

```{r}
abalone <-
  abalone_raw %>%
  rename(NA) %>% # rename
  mutate(NA)     # format
```





```{r, fig.cap = "Average weight of Tatooine born Star Wars charachters by eye color."}

```


